```{r}
packages = c("gtools","sp","sf","tidyverse","tmap","rjson", "rgdal", "geojsonio", "GISTools",'spatialEco', "raster","dplyr", "spatstat",
             'maptools',"OpenStreetMap",'tmaptools', 'leaflet', 'magick', 'purrr') 
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p) 
  } 
  library(p,character.only = T) 
}
```

```{r}

taiwan_ts_map_sp <- readOGR(dsn = "data/TAIWAN_TOWNSHIP", layer = "TOWN_MOI_1071226", stringsAsFactors=TRUE)
taiwan_ts_map_sf = st_as_sf(taiwan_ts_map_sp)

#taiwan <- readShapePoly("data/taiwan_data/")
taiwan <- readOGR(dsn = "data/taiwan_data", layer = "COUNTY_MOI_1071226", stringsAsFactors=TRUE)
taiwan@proj4string<- CRS( "+init=epsg:3826 +proj=longlat +ellps=WGS84 +no_defs")
taiwan.union <- aggregate(taiwan)
taiwan <- as(taiwan, "SpatialPolygons")
taiwan <- na.omit(taiwan)

df_dengue.raw <- jsonlite::fromJSON("data/dengue_case.json")
df_dengue.raw$ID <- seq.int(nrow(df_dengue.raw))
df_dengue.raw$Minimum_statistical_area_center_point_X <- as.numeric(paste( df_dengue.raw$Minimum_statistical_area_center_point_X))
df_dengue.raw$Minimum_statistical_area_center_point_Y <- as.numeric(paste( df_dengue.raw$Minimum_statistical_area_center_point_Y))
df_dengue = df_dengue.raw[,-c(2:9,12:25)]
df_dengue = rename(df_dengue, x = Minimum_statistical_area_center_point_X, y = Minimum_statistical_area_center_point_Y)
df_dengue <- na.omit(df_dengue)

#na_count <-sapply(df_dengue, function(y) sum(length(which(is.na(y)))))
```


```{r}
analysis_mode = "week"
# 12 months for year
start_year= 2016
# 12 weeks for months
# 14 days for day
start_date = "2016-1-1"

sigma_val = 0.5
kernel_val = "gaussian"

region = "all"

break_bin = 10
```

```{r}
date_list= list()
list_i = 1

if (analysis_mode=="month"){
  for(month in c(1:12)){
    start_date = as.Date(paste(start_year,"-",month,"-",1,sep=""))
    if(month != 12){
      end_date = as.Date(paste(start_year,"-",month+1,"-",1,sep="")) - 1
    }else{
      end_date = as.Date(paste(start_year,"-",12,"-",31,sep=""))
    }
    date_list[[list_i]] = c(paste(start_date),paste(end_date))
    list_i = list_i+1
  }
}else if(analysis_mode=="week"){
  end_date = as.Date(start_date)
  for(week in c(1:12)){
    t_start_date = end_date
    end_date = t_start_date + 6
    date_list[[list_i]] = c(paste(t_start_date),paste(end_date))

    end_date = end_date+1
    list_i = list_i+1
  }
}else if(analysis_mode=="day"){
  t_start_date = as.Date(start_date)
  for(day in c(0:13)){
    date_list[[list_i]] = c(paste(t_start_date+day),paste(t_start_date+day))
    list_i = list_i+1
  }
}else{
  print("Fallen.")
}

```

```{r}
if(region == "all"){
  tw_owin <- as(taiwan_ts_map_sp, "owin")
  tw_bb <- bb(taiwan_ts_map_sp)
}else{
  area_sf = taiwan_ts_map_sf[taiwan_ts_map_sf$TOWNENG==region,]
  area_sp = as(area_sf,"Spatial")
  tw_owin <- as(area_sp, "owin")
  tw_bb <- bb(area_sp)
}

tw_osm <- read_osm(tw_bb, type="osm")
```


```{r}
spatpoint_list= list()
list_i = 1

for(date_range in date_list){
  dengue_pt_range = df_dengue %>%
                    filter(as.Date(Onset_day) >= date_range[1] & as.Date(Onset_day)<= date_range[2])%>%
                    st_as_sf(coords = c("x","y"),
                        crs = "+init=epsg:3826 +proj=longlat +ellps=WGS84 +no_defs") %>%
                    as('Spatial') 
  spatpoint_list[[list_i]] = dengue_pt_range
  list_i = list_i + 1
}
```

```{r}
ppp_list= list()
list_i = 1

for(spatpoint in spatpoint_list){
  ppp_range = as(spatpoint_list[[list_i]],"ppp")
                    
  ppp_list[[list_i]] = ppp_range
  list_i = list_i + 1
}
```


```{r}
list_i = 1

for(ppp_range in ppp_list){
  ppp_list[[list_i]] = ppp_list[[list_i]][tw_owin]
  print(paste(round(list_i/length(ppp_list)*100,2),"%",sep=""))
  list_i = list_i + 1
}

```

```{r}
tmap_mode("plot")

if (dir.exists("plots")) {
  unlink("plots", recursive = TRUE)
}
dir.create("plots")

plot_list = list()

list_i = 1

for(ppp_range in ppp_list){
 t_kde_taiwan_bw <- density(ppp_range, sigma=sigma_val, edge=TRUE, kernel=kernel_val)
 plot_list[[list_i]] = t_kde_taiwan_bw
 print(round(list_i/length(ppp_list)*100,2))
 list_i = list_i+1
}

```

```{r}
min_val= .Machine$integer.max
max_val=0

for(plot_a in plot_list){
  plot_a$v[is.na(plot_a$v)] <- 0
 if(min(plot_a$v)<min_val){
   min_val=min(plot_a$v)
 }
  if(max(plot_a$v)>max_val){
    max_val=max(plot_a$v)
  }
}

v_range = ceiling(max_val) - floor(min_val)
r_interval = ceiling(v_range/break_bin)
bins = seq(0,r_interval*break_bin,r_interval)


list_i = 1

for(kde_taiwan_bw in plot_list){
  gridded_kde_taiwan_bw<- as.SpatialGridDataFrame.im(kde_taiwan_bw)
  
  kde_taiwan_bw_raster <- raster(gridded_kde_taiwan_bw)
  
  projection(kde_taiwan_bw_raster) =  crs(taiwan_ts_map_sf)
  
  map <- 
      tm_shape(tw_osm)+
      tm_rgb() +
      tm_shape(kde_taiwan_bw_raster)+
      tm_raster("v", alpha = 0.65, style="fixed", breaks=bins )+ 
      tm_layout(paste("Dengue Outbreak Distribution in",date_list[[list_i]][1], "to", date_list[[list_i]][2]), 
              title.size = 1, 
              title.position = c("right","top"),
              legend.title.size = 1,
              legend.text.size = 0.7,
              legend.position = c("right","bottom"))
  tmap_save(map, filename=paste("plots/plot",list_i,".png", sep="" ))
  print(paste("PNG frame saved for plot",list_i))
  list_i = list_i+1
}     
```

```{r}
plot_dir_list = list.files(path = "plots",full.names = TRUE, recursive = TRUE)
plot_dir_list = mixedsort(sort(plot_dir_list))
```


```{r}
img_list = list()
list_i = 1

for(file_n in plot_dir_list){
  img_list = append(img_list,image_read(file_n))
}

img_list <- image_scale(img_list, "500x500")
image_animate(image_scale(img_list, "500x500"), fps = 4, dispose = "previous")
  
```


