---
title: "PROJECT"
author: "Jerry Tohvan, "
date: "1/14/2019"
output: 
  html_notebook:
    number_section: yes
    theme: flatly
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---

Setup R notebook Environment
```{r setup, include=TRUE, eval=TRUE,message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
 Sys.setlocale("LC_CTYPE", "chinese")
```

#Package load for Project
```{r}
packages = c('sp','sf','tidyverse',"tmap","rjson", "rgdal", "geojsonio", "GISTools") 
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p) 
  } 
  library(p,character.only = T) 
}
```

#Importing Taiwan GDAM Subzone
Shapefile Object with Spatial data
Import data for past 12 years

Requires translation of chinese character independetly (https://stat.ethz.ch/pipermail/r-sig-geo/2009-March/005323.html)

Taiwan follows EPSG 3826 (http://spatialreference.org/ref/epsg/twd97-tm2-zone-121/)
```{r}
taiwan_map_sf <- st_read(dsn = "data/GADM_SUBZONE", layer = "gadm36_TWN_2" , stringsAsFactors=FALSE)
taiwan_map_st <- st_transform(taiwan_map_sf,crs=3826)

name_dict = read_tsv("data/clean_data/my_name_dict.csv")

a_c_g_y_Dengue = read_csv("data/clean_data/Age_County_Gender_Year_Dengue_Case_chinese.csv")

#result <- fromJSON(file = "Hospital_Geometry_City_clean.json")
# Convert JSON file to a data frame.
#json_data_frame <- as.data.frame(result)

```
Map name dict to map
```{r}
taiwan_map_bridge_lab = left_join(taiwan_map_st, name_dict[,c("GADM_NAME","GG_NAME")], by = c("NAME_2"="GADM_NAME"))
```

Transformation to plot
```{r}
#aggregate information for plotting
agg = aggregate(a_c_g_y_Dengue$num_of_case,by = list(a_c_g_y_Dengue$country,a_c_g_y_Dengue$onset_year,a_c_g_y_Dengue$incident_month),FUN = sum)
colnames(agg) = c("country","onset_year","month","num_of_case")

#Doing a sample for year 2005
n2005_sample= agg[agg$onset_year==2005,]
taiwan_2005_1= left_join(taiwan_map_bridge_lab, n2005_sample, by = c("GG_NAME"="country"))

```


##Visualise interactive Taiwan Map
```{r}
tm_shape(taiwan_map_st)+
  tm_borders(col = "grey40",alpha=0.5)+
tm_shape(taiwan_2005_1)+
  tm_polygons('num_of_case',alpha=0.5, title="Num of Cases")+
  tm_facets(by="month")
```

```{r}
new = taiwan_map_sf
st_geometry(new) <- NULL
sel = new[,c("NL_NAME_2","NAME_2")]
con = file("name_dict2.csv",encoding="UTF-8")
write.csv(sel, file=con)
```

## Visualise Hospitals With Dengue NS1 Rapid Test

```{r}
datafile <- "data/clean_data/Hospitals With Dengue NS1 Rapid Test.geojson"
hospital_sp <- geojson_read(datafile, method = "local", what="sp")

hospital_sf <- st_as_sf(hospital_sp, crs=3826)
hospital_sf <- st_transform(hospital_sf, 3826)
hospital_sp <- as(hospital_sf, 'Spatial')
#plot(hospital_sf)
```

```{r}
taiwan_map_sp <- as(taiwan_map_st, 'Spatial')

hospital_count <- poly.counts(pts = hospital_sp, polys = taiwan_map_sp)
taiwan_map_sp$hospital_count <- hospital_count
taiwan_map_st <- st_as_sf(taiwan_map_sp)
```

```{r}
tmap_mode("plot")

tm_shape(taiwan_map_st)+ 
  tm_fill("hospital_count", style = "jenks", palette = "Blues", title = "No. of Hospitals With Dengue NS1 Rapid Test in each subzone", title.size = 0.5) + 
  tm_layout(main.title = "Geographical distribution of Hospitals With Dengue NS1 Rapid Test \nby planning subzone", main.title.position = "center",main.title.size = 1, legend.height = 0.3, legend.width = 0.3,frame = TRUE) +   tm_borders(alpha = 0.5) + 
  tm_scale_bar()
```

