---
title: "PROJECT"
author: "Jerry Tohvan, Ang Kah Eng, Terence Tan, Jerry Tohvan"
date: "1/14/2019"
output: 
  html_notebook:
    number_section: yes
    theme: flatly
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---

Setup R notebook Environment
```{r setup, include=TRUE, eval=TRUE,message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setlocale("LC_CTYPE", "en_US.UTF-8")
```

#Package load for Project
```{r}
packages = c("sp","sf","tidyverse","tmap","rjson", "rgdal", "geojsonio", "GISTools",'spatialEco', "raster") 
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p) 
  } 
  library(p,character.only = T) 
}
```

#Importing Taiwan GDAM Subzone
Shapefile Object with Spatial data
Import data for past 12 years

Requires translation of chinese character independetly (https://stat.ethz.ch/pipermail/r-sig-geo/2009-March/005323.html)

Taiwan follows EPSG 3826 (http://spatialreference.org/ref/epsg/twd97-tm2-zone-121/)
```{r}
taiwan_ts_map_sp <- readOGR(dsn = "data/TAIWAN_TOWNSHIP", layer = "TOWN_MOI_1071226")
df_dengue <- jsonlite::fromJSON("data/dengue_case.json") %>% 
  filter(as.Date(Onset_day) >= "2016-01-01" & as.Date(Onset_day)< "2017-01-01")

# Check for NA values for coordinates
 sum(is.na(df_dengue$Minimum_statistical_area_center_point_X))
 sum(is.na(df_dengue$Minimum_statistical_area_center_point_Y))
 df_dengue<- df_dengue[!is.na(df_dengue$Minimum_statistical_area_center_point_X),]
 df_dengue<- df_dengue[!(df_dengue$Minimum_statistical_area_center_point_X == 'None'),]
 
 # Type conversion
 df_dengue[, c(10,11,19,23,24)] <- sapply(df_dengue[, c(10,11,19,23,24)], as.numeric)
 
  # Transform into SF object
 sf_dengue <- st_as_sf(df_dengue, 
                       coords = c("Minimum_statistical_area_center_point_X",
                                  "Minimum_statistical_area_center_point_Y"),
                        crs = "+init=epsg:3826 +proj=longlat +ellps=WGS84 +no_defs",na.fail=FALSE)
sf_dengue <- na.omit(sf_dengue)
sf_dengue <- as(sf_dengue, 'Spatial')
```

Map name dict to map
```{r}

#plot(taiwan_ts_map_sp, border="lightgrey")
#plot(transaction.boundary.poly, col="red",add=TRUE)

tmap_mode("plot")
map <- tm_shape(taiwan_ts_map_sp)+
      tm_polygons('TOWNENG')+
       tm_borders(col = "grey40",alpha=0.5)+
  tm_view(alpha = 1)+
  tm_layout(basemaps = c('OpenStreetMap'))+
  tm_shape(sf_dengue)+
  tm_bubbles(col ="red",size = 0.1)

map 
```


```{r}
tmap_mode("view")
map 

```



